# Generated by Django 4.0.4 on 2022-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_product_title_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
